---
apiVersion: v1
kind: Service
metadata:
  name: my-service1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # or "elb" for ALB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-app